export const en = {
  nav: {
    brand: 'VALMATA',
    subtitle: 'Educational math programs',
    langRu: 'RU',
    langKz: 'KZ',
    langEn: 'EN',
  },
  catalog: {
    title: 'Educational Programs',
    desc: 'Choose the course you need to download the installer and purchase a license key.',
    loading: 'Loading catalog...',
    empty: 'Catalog is empty',
    emptyDesc: 'Programs coming soon.',
    btnDownload: 'Download',
    btnBuy: 'Buy',
    btnMore: 'Learn more',
    btnHide: 'Hide',
    private: 'Private',
    corporate: 'Corporate',
    perMonth: 'mo.',
    comingSoon: 'soon',
  },
  buy: {
    title: 'Purchase License',
    privateTab: 'Private',
    corporateTab: 'Corporate',
    nameLabel: 'Your name',
    periodLabel: 'Subscription period',
    totalLabel: 'Total',
    btnPay: 'Proceed to payment',
    redirect: 'Redirecting...',
    secureNote: 'Secure payment via Lemon Squeezy. Card details are not shared with the seller.',

    activationDataTitle: 'Activation data',
    emailLabel: 'Email',
    hwidLabel: 'Device code (HWID)',
    infoTitle: 'Why we need this:',
    infoEmail: '• Email — the activation key will be sent to it after payment.',
    infoHwid: '• HWID — links the license to your computer. The code is shown in the MathApp.',
    errorEmail: 'Please enter a valid email.',
    errorHwid: 'Please enter the device code (HWID). It is shown in the MathApp.',
  },
  activate: {
    title: 'Recover license key',
    desc: 'Lost the email with your key? Enter the email you used at purchase and your device code (HWID).',
    emailLabel: 'Purchase email',
    hwidLabel: 'Device code (HWID)',
    hwidHint: 'The code is shown in the MathApp on first launch.',
    btnSubmit: 'Get key',
    loading: 'Sending...',
    back: 'Home',
    linkFromCatalog: 'Already purchased? Recover your key',
    successTitle: 'Activation key received',
    keyLabel: 'Activation key',
    expiresLabel: 'Valid until',
    emailHint: 'A copy of the key has been sent to the specified email.',
    errorGeneric: 'Failed to get the key. Please check your data.',
    errorNetwork: 'Network error. Please try again later.',
  },
  footer: { copyright: '© 2026 VALMATA. All rights reserved.' },
};