export const kz = {
  nav: { brand: 'Математика', langRu: 'RU', langKz: 'KZ', langEn: 'EN' },
  catalog: {
    title: 'Білім беру бағдарламалары',
    desc: 'Орнатушыны жүктеп алу және лицензия кілтін сатып алу үшін қажетті курсты таңдаңыз.',
    loading: 'Каталог жүктелуде...',
    empty: 'Каталог бос',
    emptyDesc: 'Бағдарламалар жақында пайда болады.',
    btnDownload: 'Жүктеу',
    btnBuy: 'Сатып алу',
    btnMore: 'Толығырақ',
    btnHide: 'Жасыру',
    private: 'Жеке',
    corporate: 'Корпоративтік',
    perMonth: 'ай',
    comingSoon: 'жақында',
  },
  buy: {
    title: 'Лицензияны сатып алу',
    privateTab: 'Жеке',
    corporateTab: 'Корпоративтік',
    nameLabel: 'Сіздің атыңыз',
    periodLabel: 'Жазылу мерзімі',
    totalLabel: 'Барлығы',
    btnPay: 'Төлеуге өту',
    redirect: 'Қайта бағыттау...',
    secureNote: 'Lemon Squeezy арқылы қауіпсіз төлем. Карта деректері сатушыға берілмейді.',
  },
  activate: {
    title: 'Кілтті белсендіру',
    desc: 'Сатып алу кезінде қолданған emailді және құрылғы кодын (HWID) енгізіңіз.',
    emailLabel: 'Сатып алу кезіндегі email',
    hwidLabel: 'Құрылғы коды (HWID)',
    hwidHint: 'Код MathApp қосымшасында бірінші іске қосқанда көрсетіледі.',
    btnSubmit: 'Кілт алу',
    loading: 'Жіберілуде...',
    back: 'Басты бетке',
    linkFromCatalog: 'Сатып алдыңыз ба? Кілтті белсендіру',
    successTitle: 'Белсендіру кілті алынды',
    keyLabel: 'Белсендіру кілті',
    expiresLabel: 'Мерзімі',
    emailHint: 'Кілттің көшірмесі көрсетілген emailге жіберілді.',
    errorGeneric: 'Кілт алу мүмкін болмады. Деректерді тексеріңіз.',
    errorNetwork: 'Желі қатесі. Кейінірек қайталап көріңіз.',
  },
  footer: { copyright: '© 2026 Білім беру платформасы' },
};