export const ru = {
  nav: { brand: 'Математика', langRu: 'RU', langKz: 'KZ', langEn: 'EN' },
  catalog: {
    title: 'Образовательные программы',
    desc: 'Выберите нужный курс для скачивания установщика и приобретения лицензионного ключа.',
    loading: 'Загрузка каталога...',
    empty: 'Каталог пуст',
    emptyDesc: 'Программы скоро появятся.',
    btnDownload: 'Скачать',
    btnBuy: 'Купить',
    btnMore: 'Подробнее',
    btnHide: 'Свернуть',
    private: 'Частная',
    corporate: 'Корпоративная',
    perMonth: 'мес.',
    comingSoon: 'скоро',
  },
  buy: {
    title: 'Покупка лицензии',
    privateTab: 'Частная',
    corporateTab: 'Корпоративная',
    nameLabel: 'Ваше имя',
    periodLabel: 'Период подписки',
    totalLabel: 'Итого',
    btnPay: 'Перейти к оплате',
    redirect: 'Перенаправление...',
    secureNote: 'Безопасная оплата через Lemon Squeezy. Данные карты не передаются продавцу.',
  },
  activate: {
    title: 'Активация ключа',
    desc: 'Введите email, который использовали при покупке, и код вашего устройства (HWID).',
    emailLabel: 'Email при покупке',
    hwidLabel: 'Код устройства (HWID)',
    hwidHint: 'Код показывается в приложении MathApp при первом запуске.',
    btnSubmit: 'Получить ключ',
    loading: 'Отправка...',
    back: 'На главную',
    linkFromCatalog: 'Уже купили? Активировать ключ',
    successTitle: 'Ключ активации получен',
    keyLabel: 'Ключ активации',
    expiresLabel: 'Действует до',
    emailHint: 'Копия ключа отправлена на указанный email.',
    errorGeneric: 'Не удалось получить ключ. Проверьте данные.',
    errorNetwork: 'Ошибка сети. Попробуйте позже.',
  },
  footer: { copyright: '© 2026 Образовательная платформа' },
};